### ISSUE TITLE
Some fixes for modded servers

### ISSUE THREAD

**Issue by pingvikin** [Extegral/Forgotten-Relics#10]
Hello!
You make cool and great mod, i make server for my friends. I tested all 35 items of the mod and find 10 items with some problems for server-side. Are you can fix them please?

1. Tome of Primal Chaos - Need Cooldowns of using + events for WorldGuard
2. Tome of Discord - Configurable working with only mobs and monsters + events for WorldGuard
3. Eldritch Spell - events for WorldGuard
4. Edict of Eternal Banishment - Need Cooldowns of using, events for WorldGuard + serching safe place for teleporting
5. Tome of Predestiny - events for WorldGuard
6. Tome of Lunar Flares - events for WorldGuard (can push mobs from region)
7. Grimoire of The Abyss - Configurable working with only mobs and monsters + events for WorldGuard
8. Runic Stone - Global cooldown for all players on the server
9. Crown of Terror - events for WorldGuard (can debafe player of mobs in region)
10. Dimensional Mirror - cooldown + price in vis for using 

Events - I think that these items do things on behalf of the mod, not the player. Since the rest of the items - no problem.
But if this is not the case, then as a rule you can create a server build of the mod by importing code from the EventHelper library into it. This will definitely prevent foreign players from interacting with the regions.

Also, what mean memes?
![image](https://user-images.githubusercontent.com/26678843/80929158-62d45880-8db2-11ea-9d34-601592a4824d.png)

**Comment by Extegral** [comment]
Bold of you to assume I am interested in compatibility with WolrdGuard. Although I am.

I shall address this some time soon and make separate release including EventHelper integration here on github. In the meantime, you may submit other issues, if you will happen to find more.

Regarding memes... I'm afraid I can't tell ¯\_(ツ)_/¯

**Comment by Extegral** [comment]
Bold of you to assume I care about compatibility with World Guard.

I can take care of that and make private, more server-friendly version utilizing gamerforEA's EventHelper and implementing stuff like per-player/global cooldowns for some items, but that comes at a cost.

If you're interested, contact me personally, my E-Mail: VictorShadow-Integral@yandex.ru
