### ISSUE TITLE
Crash with spellbooks

### ISSUE THREAD

**Issue by GedeonGrays** [Extegral/Forgotten-Relics#2]
Происходит краш при использовании Гримуара бездны или Эдикта вечного изгнания на Кристалле Края.
[crash-server](https://pastebin.com/eZGD2rn1)
[crash-client](https://pastebin.com/876t7QKm)
Версия Forgotten Relics: 1.4.0
Версия Thaumcraft: 4.2.3.5
Версия Botania: r1.8-249

**Comment by Extegral** [comment]
Оу щит. Окей, исправлю сегодня

**Comment by Extegral** [comment]
Пофиксил в 1.4.1.

**Comment by GedeonGrays** [comment]
Оперативненько :3
