### ISSUE TITLE
Suggestion: Config for Research trigger items?

### ISSUE THREAD

**Issue by bloche14** [Extegral/Forgotten-Relics#3]
Could we get a config option for which items are required to scan for unlocking each forgotten knowledge research?

**Comment by Extegral** [comment]
The idea sounds reasonable, but it's one of those things that are much easier to say rather than implement. I'll look if I can make something like this, but such an option most probably won't come with nearest updates.

**Comment by Extegral** [comment]
I had some hard time designing an elegant solution, but at least this task turned out to be much more completable that I expected it to be.
The option is implemented in 1.5.3. Hope it would be useful for someone.

**Comment by bloche14** [comment]
Thank you!

**Comment by Extegral** [comment]
Now you have one more way of doing that. Check out the MineTweaker Integration article here on wiki.
