### ISSUE TITLE
Possible bug with Keystone of The Oblivion

### ISSUE THREAD

**Issue by GedeonGrays** [Extegral/Forgotten-Relics#4]
С режимом Ключ-камня Забвения "Последний стак" происходит что-то странное. По-моему, он не совсем правильно работает. 
В общем, если в каком-то слоте инвентаря лежит целый стак, например, песка, и выходит так, что следующий добытый блок песка попадает в слот после того слота, в котором лежит стак песка, целый стак поглощается ключ-камнем, вместо последнего добытого блока песка. Я считаю, что это не совсем разумное поведение, логичнее было бы, чтобы забирался последний блок, а стак оставался независимо от слота, в котором он лежит. Было проверено с землёй, песком, песчаником и булыжником. 
Версия Forgotten Relics: 1.5.1
Версия Thaumcraft: 4.2.3.5
Версия Botania: r1.8-249

**Comment by Extegral** [comment]
Это зависит от того, в каком слоте он лежит. Если не ошибаюсь, инвентарь проверяется слева направо и сверху вниз, при этом сначала хотбар, а уже потом остальные 27 слотов.
Я технически не могу сделать, что бы он запоминал, в каком слоте лежит какой стак. Могу только обратить порядок проверки, и/или сделать так что бы он предпочитал поглощать стаки с меньшим количеством предметов.

**Comment by GedeonGrays** [comment]
Благодарю за скорый ответ.
Последний вариант лично мне кажется наиболее приемлемым выходом из ситуации. Если вас это не затруднит, реализуйте, пожалуйста, поглощение стаков с меньшим количеством предметов.

**Comment by Extegral** [comment]
Окей, будет сделано

**Comment by GedeonGrays** [comment]
Огромное спасибо, буду ждать следующего обновления.

**Comment by Extegral** [comment]
Сделано в апдейте 1.5.2. Рекомендую прочесть чейнджлог, там описано по каким параметрам теперь ключ-камень определяет приоритетные стаки.
