### ISSUE TITLE
Deific Amulet nullifying potion effects. 

### ISSUE THREAD

**Issue by Sondz1** [Extegral/Forgotten-Relics#5]
I'm unsure if this was intended, but the Deific Amulet will negate positive potion effects (Haste, Strenght, Regeneration, a few modded effects from Automagy such as Vis Generation). This makes a few runic shielding effects useless and makes potion brewing completely useless. If this isn't intended I'd strongly urge you to reconsider, because Thaumic Tinkerer's Talisman of Remedium would be a straight up upgrade to the Amulet, as it allows you to use potion effects whilst filtering out negative warp effects.

**Comment by Sondz1** [comment]
Thank you for the very quick reply (and also thank you for being one of the few modders to still continue supporting 1.7.10). 
I'd like to just mention an interesting bug in the final version of TT, ToR actually has **unlimited** durability thanks to a glitch that resets its durability when it hits 0. I know it might not be relevant or something, but I guess it might be interesting.

**Comment by Extegral** [comment]
Nothing that special to thank for.

Well, that's the curious bug. But the bug is still just the bug - sometimes things may not work as they intended to.
What's about said above? I mean, should I add that config option that I mentioned?

**Comment by Sondz1** [comment]
Yes, adding a config that enables it to only remove debuffs would be great. If you feel like this is cheaty, you could consider adding a vis cost (lets say, terra, aqua, ordo (because terra and aqua form victus, victus and ordo give sano)).

**Comment by Extegral** [comment]
Alright. I'll look for best way to implement this.
Expect it with next update.

**Comment by Extegral** [comment]
Implemented in 1.6.2.
