### ISSUE TITLE
"Level up" version.

### ISSUE THREAD

**Issue by shoverno2** [Extegral/Forgotten-Relics#7]
I understand that almost anything in this addon working only with 1.7.10 version.
But there so many cool artifacts, so brilliant! Just why not to bring that addon to 1.12.2 version too? I don't "discriminate" 1.7.10 version(Still like those stuffs, still like taint magic...), but this mod enough awesome, it's should be advansed for 1.12.2 too...

**Comment by Extegral** [comment]
Currently, I have lost my primary inspiration and interest in the mod and mostly abandoned it. I will work over some final bugfixes and overall code cleanup this weekend, but that's gonna be all for now.

I am not leaving it forever - perhaps, someday I will come back to continue the development, perhaps on newer versions of Minecraft, too. But not gonna promise anything just yet.

**Comment by shoverno2** [comment]
It's something like suggestions. You don't need to promise)
I understand all)

**Comment by Extegral** [comment]
Fine.
